services:
  api-dev:
    container_name: api-dev
    build:
      context: .
      target: development
    volumes:
      - api_sources:/api
    develop:
      watch:
        - action: sync
          path: .
          target: /api
        - action: rebuild
          path: package.json
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres-dev
    ports:
      - 3000:3000
    depends_on:
      - postgres-dev
    command: npm run start:dev
    profiles:
      - dev

  api-prod:
    container_name: api-prod
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres-prod
      - TYPEORM_MIGRATIONS_RUN=true
    ports:
      - 3001:3000
    depends_on:
      - postgres-prod
    profiles:
      - prod

  postgres-dev:
    container_name: postgres-dev
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    profiles:
      - dev

  postgres-prod:
    container_name: postgres-prod
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - postgres-prod:/var/lib/postgresql/data
    profiles:
      - prod

volumes:
  api_sources:
  postgres-dev:
  postgres-prod: