services:
  api-development:
    container_name: api-development
    build:
      context: .
      target: development
    volumes:
      - api_sources:/api
    develop:
      watch:
        - action: sync
          path: .
          target: /api
        - action: rebuild
          path: package.json
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: npm run start:dev
    profiles:
      - dev

  api-production:
    container_name: api-production
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      - TYPEORM_MIGRATIONS_RUN=true
    ports:
      - 3000:3000
    depends_on:
      - postgres
    profiles:
      - prod

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  api_sources:
  postgres: